management-api:
  config:
    tlsClientCSRParametersData: |-
      {
        "subject": {
          "emailAddress": "test@test.com",
          "ST": "test_client",
              "C": "US",
              "L": "test",
              "O": "test",
              "CN": "test_client",
              "OU": "test"
        },
        "extensions": {
          "subjectAltName": {
            "dns": [
              "test"
            ],
            "ips": [
              "test"
            ]
          }
        }
      }
    tlsServerCSRParametersData: |-
      {
        "subject": {
          "emailAddress": "test@test.com",
          "ST": "test_server",
              "C": "US",
              "L": "test",
              "O": "test",
              "CN": "test_server",
              "OU": "test"
        },
        "extensions": {
          "subjectAltName": {
            "dns": [
              "test"
            ],
            "ips": [
              "test"
            ]
          }
        }
      }
      
mojaloop-core-connector:
  image:
    repository: pm4ml/wallet-core-connector
    tag: 1.0.10
  env:
    MLCONN_OUTBOUND_ENDPOINT: "http://{{ item.value.helm_release_name }}-pm4ml-mojaloop-connector:4001"
    BACKEND_ENDPOINT: "http://sim-backend:3000"
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

pm4ml-mojaloop-connector:
  env:
    RESOURCE_VERSIONS: transfers=1.1,
    RESERVE_NOTIFICATION: true
    AUTO_ACCEPT_PARTY: true
    AUTO_ACCEPT_QUOTES: true